version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdata
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mynetwork

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./code:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    build: .
    restart: always
    volumes:
      - ./code:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
